import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import AllProviders from "@/shared/providers/AllProviders";
import NavBar from "@/shared/components/nav-bar";

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"], // 400=Regular, 500=Medium, 600=Semi-Bold, 700=Bold
  variable: "--font-cairo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Moonlight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cairo.variable} scrollbar-hide`}>
      <head>
        <link
          rel="preload"
          as="video"
          fetchPriority="high"
          href="/videos/HeroSection.webm"
          type="video/webm"
        />
      </head>
      <body className="antialiased">
        <AllProviders>
          <NavBar />
          {children}
        </AllProviders>
      </body>
    </html>
  );
}
