import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
export const dynamic = "force-static";
export const dynamicParams = false;

export async function generateStaticParams() {
  return ["en", "fr", "it", "es", "pt"].map((locale) => ({ locale }));
}
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"], // 400=Regular, 500=Medium, 600=Semi-Bold, 700=Bold
  variable: "--font-cairo",
  display: "swap",
});
export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_WEBSITE_URL || "http://localhost:3000",
  ),
  title: "Moonlight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cairo.variable} scrollbar-hide`}>
      <body>{children}</body>
    </html>
  );
}
